### ISSUE TITLE
Copright

### ISSUE THREAD

**Issue by aarong2003** [CodeSequence/sanmyaku#45]
Hi,
just wondering if I can remove the copyright on this theme?
Thanks, Aarong

**Comment by krjordan** [comment]
Sure, go for it.

**Comment by valeryan** [comment]
@krjordan I think the question is because in our[ MIT License](https://github.com/CodeSequence/sanmyaku/blob/master/LICENSE.md) states that the copyright should not be removed. We should amend it say we are cool with whatever changes you want to make for your own site but if you want to redistribute the theme with something it needs to have a link back to the theme and include its license and legal blah blah...

**Comment by aarong2003** [comment]
Hi,
Thanks for your responses. I really appreciate it. I wanted to use the theme for my website debateisland.com. It's through vanilla. Your theme looks really nice so I wanted to consider using it. Good job on the theme. Please let me know if I can use it form my website without the copyright.
Thanks, Aarong
